# Generated by Django 3.0.3 on 2020-02-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_locator_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
    ]
