# Generated by Django 3.0.3 on 2020-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_locator_app', '0002_remove_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=None)),
                ('spot_type', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
