# Generated by Django 3.0.3 on 2020-02-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_locator_app', '0003_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='spot_type',
        ),
        migrations.CreateModel(
            name='Descriptors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='shoot_locator_app.Marker')),
            ],
        ),
    ]
