# Generated by Django 3.0.3 on 2020-02-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_locator_app', '0004_auto_20200220_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Descriptors',
        ),
    ]
