# Generated by Django 3.0.3 on 2020-02-20 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_locator_app', '0005_delete_descriptors'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='descriptors',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
